spring.application.name=${APP_NAME}
server.port=${APP_PORT}

openai.api.key=${OPENAI_API_KEY}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.mapper.sort-properties-alphabetically=false

cloudflare.api.token=${CLOUDFLARE_API_TOKEN}
cloudflare.account.id=${CLOUDFLARE_ACCOUNT_ID}
cloudflare.model=${CLOUDFLARE_MODEL}

wa_server=${WA_SERVER}